# Generated by Django 4.2.7 on 2024-03-29 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postform_publish_postform_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postform',
            name='email',
        ),
        migrations.AddField(
            model_name='postform',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postform',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
